version: '3.7'

networks:
  gateway:
    external: true
    name: gateway

services:
  double-take:
    container_name: double-take
    image: jakowenko/double-take
    restart: unless-stopped
    volumes:
      - $INSTALL_DIR/storage:/.storage
    networks:
      - gateway
    logging:
      driver: syslog
      options:
        syslog-address: "udp://172.16.20.11:7514"
        syslog-format: "rfc3164"
        tag: "double-take"